### ISSUE TITLE
R6-Bot

### ISSUE THREAD

**Issue by Brunituns** [hmes98318/r6s-stats#17]
Hello hmes!! I love the work you did, I have a question im new into all of this of discord bots, Im a mechatronic engineer. I was wondering if there's any way to give a user on discord their R6 Rank as a Role on the server after they submit their username, i would really appreciate if you could help me out with this

**Comment by hmes98318** [comment]
Hey Brunituns, you can use the rank function of this API to obtain the user’s rank, and then use the role function of discord.js to assign roles. However, I am not familiar with role assignment in discord.js, so I may not be able to help much.

**Comment by Brunituns** [comment]
It will be a challenge first i have to understand how to create disc bots and then look at the discord.js to figure out the rest. Thanks for the reply!!
